const KEY='familyMealPwaDataV1';
const money=n=>new Intl.NumberFormat('ko-KR').format(Math.round(n||0))+'원';
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const nowMonth=()=>new Date().toISOString().slice(0,7);

const demoPlan={
 month:nowMonth(), basePeople:6,
 meals:Array.from({length:30},(_,i)=>{const menus=[
  ['계란토스트·우유','제육볶음','김치찌개'],
  ['소고기채소죽','닭갈비','고등어구이'],
  ['참치주먹밥·과일','카레라이스','삼겹살구이'],
  ['달걀볶음밥','소불고기','순두부찌개'],
  ['햄치즈샌드위치','돈까스','김치볶음밥'],
  ['바나나오트밀','닭볶음탕','계란찜'],
  ['김치콩나물국밥','오징어볶음','부대찌개']
 ][i%7];return {day:i+1,breakfast:menus[0],lunch:menus[1],dinner:menus[2],prep:i%3===0?'고기 1팩 냉장 해동':'필요 채소와 양념 확인'};}),
 recipes:{
 '계란토스트·우유':{time:15,difficulty:'쉬움',summary:'바쁜 아침에 15분이면 완성되는 든든한 토스트',ingredients:[['식빵',6,'장'],['계란',6,'개'],['우유',1.2,'L'],['슬라이스치즈',6,'장'],['버터',30,'g']],prep:['계란은 미리 풀어 소금 한 꼬집을 넣습니다.','식빵과 치즈를 조리대에 꺼내 둡니다.'],steps:['중약불로 달군 팬에 버터 절반을 녹입니다.','식빵을 앞뒤로 1분씩 노릇하게 굽습니다.','남은 버터를 넣고 계란물을 부어 부드럽게 익힙니다.','식빵 위에 계란과 치즈를 올려 반으로 접습니다.','우유와 함께 바로 냅니다.'],tips:['계란은 센 불보다 중약불에서 익혀야 촉촉합니다.','아이용은 케첩을 소량 곁들여도 좋습니다.']},
 '소고기채소죽':{time:35,difficulty:'보통',summary:'속이 편하고 포만감이 오래가는 아침죽',ingredients:[['쌀',0.45,'kg'],['소불고기',0.35,'kg'],['당근',0.15,'kg'],['양파',0.2,'kg'],['참기름',20,'ml']],prep:['쌀은 씻어 20분 불립니다.','소고기와 채소는 잘게 다집니다.'],steps:['냄비에 참기름을 두르고 소고기를 핏기가 사라질 때까지 볶습니다.','양파와 당근을 넣어 2분 더 볶습니다.','불린 쌀을 넣고 쌀알이 반투명해질 때까지 볶습니다.','물 2.5L를 넣고 센 불에서 끓입니다.','끓기 시작하면 약불로 줄여 20분간 저으며 끓입니다.','소금으로 간하고 5분 뜸을 들입니다.'],tips:['남은 밥으로 만들면 조리시간을 15분 정도 줄일 수 있습니다.']},
 '참치주먹밥·과일':{time:15,difficulty:'쉬움',summary:'아이들도 먹기 편한 한입 아침',ingredients:[['밥',1.2,'kg'],['참치캔',2,'캔'],['김가루',30,'g'],['마요네즈',60,'g'],['바나나',6,'개']],prep:['참치는 기름을 충분히 뺍니다.','밥은 뜨겁지 않게 한 김 식힙니다.'],steps:['큰 볼에 밥, 참치, 김가루, 마요네즈를 넣습니다.','밥알이 으깨지지 않도록 주걱으로 가볍게 섞습니다.','한입 크기로 단단하게 뭉칩니다.','바나나 또는 계절 과일과 함께 냅니다.'],tips:['전날 만들어 냉장 보관했다면 전자레인지에 살짝 데워 드세요.']},
 '달걀볶음밥':{time:20,difficulty:'쉬움',summary:'냉장고 자투리 채소를 활용하기 좋은 한 그릇 메뉴',ingredients:[['밥',1.2,'kg'],['계란',8,'개'],['대파',0.3,'단'],['당근',0.15,'kg'],['식용유',40,'ml']],prep:['찬밥은 덩어리를 풀어 둡니다.','대파와 당근은 잘게 썹니다.'],steps:['팬을 충분히 달군 뒤 식용유를 두릅니다.','계란을 넣어 70% 정도만 익혀 따로 덜어 둡니다.','같은 팬에 대파와 당근을 2분간 볶습니다.','밥을 넣고 센 불에서 3분간 고슬고슬하게 볶습니다.','계란을 다시 넣고 소금과 간장으로 간합니다.'],tips:['밥이 너무 질면 전자레인지에 1분 데워 수분을 날린 뒤 볶습니다.']},
 '햄치즈샌드위치':{time:15,difficulty:'쉬움',summary:'불 없이도 만들 수 있는 간단한 아침',ingredients:[['식빵',12,'장'],['슬라이스햄',6,'장'],['슬라이스치즈',6,'장'],['상추',1,'봉'],['마요네즈',50,'g']],prep:['상추는 씻어 물기를 완전히 제거합니다.'],steps:['식빵 한쪽 면에 마요네즈를 얇게 바릅니다.','상추, 햄, 치즈 순서로 올립니다.','다른 식빵을 덮고 살짝 눌러 고정합니다.','대각선으로 잘라 먹기 좋게 냅니다.'],tips:['오래 두면 상추 수분으로 빵이 눅눅해지므로 먹기 직전에 만듭니다.']},
 '바나나오트밀':{time:10,difficulty:'매우 쉬움',summary:'설거지가 적고 포만감이 좋은 초간단 아침',ingredients:[['오트밀',0.36,'kg'],['우유',1.2,'L'],['바나나',6,'개'],['견과류',60,'g']],prep:['바나나는 얇게 썹니다.'],steps:['냄비에 오트밀과 우유를 넣습니다.','중약불에서 5~6분간 저으며 끓입니다.','걸쭉해지면 불을 끄고 그릇에 나눕니다.','바나나와 견과류를 올립니다.'],tips:['단맛이 부족하면 꿀을 1작은술씩 추가합니다.']},
 '김치콩나물국밥':{time:30,difficulty:'보통',summary:'국물과 밥을 한 번에 해결하는 든든한 아침',ingredients:[['김치',0.5,'kg'],['콩나물',0.6,'kg'],['밥',1.2,'kg'],['계란',6,'개'],['대파',0.3,'단']],prep:['콩나물은 씻어 물기를 뺍니다.','김치는 먹기 좋게 썹니다.'],steps:['냄비에 물 2.5L와 김치를 넣고 10분 끓입니다.','콩나물을 넣고 뚜껑을 연 채 7분 끓입니다.','국간장과 소금으로 간을 맞춥니다.','밥을 넣고 3분 더 끓입니다.','계란을 깨 넣고 대파를 올린 뒤 2분 익힙니다.'],tips:['콩나물을 넣은 뒤에는 비린내 방지를 위해 뚜껑을 계속 열어 둡니다.']},
 '제육볶음':{time:35,difficulty:'보통',summary:'매콤달콤한 양념이 고기에 잘 배는 가족 대표 메뉴',ingredients:[['돼지 앞다리살',1,'kg'],['양파',0.4,'kg'],['대파',0.2,'단'],['고추장',120,'g'],['고춧가루',40,'g'],['진간장',60,'ml'],['설탕',35,'g'],['다진마늘',35,'g'],['참기름',20,'ml']],prep:['돼지고기는 키친타월로 핏물을 닦습니다.','양파는 1cm 두께, 대파는 어슷썹니다.','고추장·고춧가루·간장·설탕·마늘·참기름을 섞어 양념을 만듭니다.'],steps:['돼지고기에 양념의 80%를 넣고 15분 이상 재웁니다.','팬을 센 불로 2분간 충분히 달굽니다.','고기를 넓게 펼쳐 넣고 2분간 건드리지 않아 갈색 면을 만듭니다.','고기를 뒤집어 3분간 볶은 뒤 양파를 넣습니다.','양파가 투명해지면 남은 양념과 대파를 넣고 2~3분 더 볶습니다.','고기가 완전히 익고 양념이 윤기 있게 졸아들면 불을 끕니다.'],tips:['물이 많이 생기면 재료를 나눠 볶아야 불맛이 납니다.','아이와 함께 먹을 경우 고춧가루를 절반으로 줄입니다.'],serving:'상추, 깻잎, 마늘과 함께 내면 균형이 좋습니다.'},
 '김치찌개':{time:45,difficulty:'보통',summary:'김치를 충분히 볶아 깊은 맛을 내는 돼지고기 김치찌개',ingredients:[['김치',0.8,'kg'],['돼지 앞다리살',0.5,'kg'],['두부',1,'모'],['양파',0.25,'kg'],['대파',0.2,'단'],['고춧가루',25,'g'],['국간장',25,'ml']],prep:['김치는 4cm 길이로 자릅니다.','두부는 1.5cm 두께로 썹니다.'],steps:['냄비에 돼지고기를 넣고 중불에서 기름이 나올 때까지 4분 볶습니다.','김치를 넣고 5분 이상 충분히 볶습니다.','고춧가루를 넣고 30초 볶아 향을 냅니다.','물 2L를 붓고 센 불에서 끓입니다.','끓으면 중약불로 줄여 20분간 푹 끓입니다.','양파와 두부를 넣고 7분 더 끓입니다.','국간장으로 간하고 대파를 넣어 마무리합니다.'],tips:['신김치가 아니면 식초 1작은술을 마지막에 넣으면 맛이 선명해집니다.']},
 '닭갈비':{time:40,difficulty:'보통',summary:'닭다리살과 채소를 한 팬에서 볶는 푸짐한 메뉴',ingredients:[['닭다리살',1,'kg'],['양배추',0.5,'통'],['양파',0.3,'kg'],['고구마',0.4,'kg'],['고추장',100,'g'],['고춧가루',35,'g'],['진간장',50,'ml'],['설탕',30,'g']],prep:['닭은 한입 크기로 자릅니다.','고구마는 0.5cm 두께로 썰어 찬물에 담급니다.'],steps:['양념 재료를 모두 섞고 닭에 절반을 버무려 15분 재웁니다.','큰 팬에 닭과 고구마를 넣고 중불에서 8분 익힙니다.','양배추와 양파, 남은 양념을 넣습니다.','센 불에서 7~8분간 골고루 뒤집어 볶습니다.','닭 중심부까지 익으면 대파를 넣고 1분 더 볶습니다.'],tips:['마지막에 밥과 김가루를 넣어 볶음밥으로 활용할 수 있습니다.']},
 '고등어구이':{time:25,difficulty:'쉬움',summary:'비린내는 줄이고 껍질은 바삭하게 굽는 방법',ingredients:[['고등어',3,'토막'],['소금',12,'g'],['식용유',20,'ml'],['레몬',0.5,'개']],prep:['고등어의 물기를 키친타월로 완전히 닦습니다.','살 쪽에 소금을 뿌려 10분 둔 뒤 다시 물기를 닦습니다.'],steps:['팬을 중불로 예열하고 식용유를 얇게 두릅니다.','고등어 껍질 쪽을 아래로 놓고 6분간 굽습니다.','뒤집어 살 쪽을 4~5분 굽습니다.','가장 두꺼운 부분을 젓가락으로 찔러 투명한 육즙이 나오면 익은 것입니다.','레몬을 곁들여 바로 냅니다.'],tips:['팬 뚜껑을 완전히 닫으면 눅눅해지므로 살짝 걸쳐 둡니다.']},
 '카레라이스':{time:45,difficulty:'쉬움',summary:'재료 크기를 맞춰 골고루 익히는 기본 카레',ingredients:[['돼지 앞다리살',0.5,'kg'],['감자',0.6,'kg'],['양파',0.5,'kg'],['당근',0.3,'kg'],['카레',1,'팩'],['밥',1.2,'kg']],prep:['고기와 채소는 모두 2cm 크기로 맞춰 썹니다.'],steps:['냄비에 기름을 두르고 양파를 중불에서 5분 볶습니다.','돼지고기를 넣고 겉면이 익을 때까지 볶습니다.','감자와 당근을 넣고 3분 더 볶습니다.','물 1.8L를 붓고 끓으면 거품을 걷습니다.','중불에서 15분간 끓여 채소를 익힙니다.','불을 끄고 카레를 나눠 넣어 완전히 풉니다.','약불에서 5분 더 저어 농도를 맞춥니다.'],tips:['카레를 넣을 때 불을 끄면 덩어리가 덜 생깁니다.']},
 '삼겹살구이':{time:30,difficulty:'쉬움',summary:'기름은 덜 튀고 겉은 노릇하게 굽는 삼겹살',ingredients:[['삼겹살',1.2,'kg'],['상추',2,'봉'],['마늘',0.15,'kg'],['쌈장',150,'g']],prep:['고기는 굽기 20분 전에 꺼내 냉기를 뺍니다.','상추는 씻어 물기를 뺍니다.'],steps:['팬을 중불로 충분히 달굽니다.','삼겹살을 겹치지 않게 올려 첫 면을 3분 굽습니다.','뒤집어 2분 굽고 먹기 좋은 크기로 자릅니다.','잘린 면을 1분씩 추가로 굽습니다.','팬의 기름을 중간중간 닦고 마늘을 함께 굽습니다.'],tips:['고기를 자주 뒤집지 않아야 육즙이 빠지지 않습니다.']},
 '소불고기':{time:40,difficulty:'보통',summary:'짭조름하지 않고 부드럽게 만드는 가족용 불고기',ingredients:[['소불고기',1,'kg'],['양파',0.4,'kg'],['대파',0.2,'단'],['진간장',100,'ml'],['배즙',120,'ml'],['설탕',35,'g'],['다진마늘',30,'g'],['참기름',20,'ml']],prep:['소고기는 키친타월로 핏물을 닦습니다.','양념을 미리 섞습니다.'],steps:['소고기에 양념을 넣고 결을 풀어가며 버무립니다.','냉장고에서 20분 재웁니다.','달군 팬에 고기를 절반씩 나눠 넣습니다.','센 불에서 3분간 빠르게 볶습니다.','양파와 대파를 넣고 2~3분 더 볶습니다.','국물이 자작하게 남을 때 불을 끕니다.'],tips:['한꺼번에 많이 넣으면 삶아지므로 두 번 나눠 볶습니다.']},
 '순두부찌개':{time:30,difficulty:'보통',summary:'고추기름을 먼저 내어 국물 맛이 진한 순두부찌개',ingredients:[['순두부',3,'봉'],['계란',2,'개'],['돼지 앞다리살',0.3,'kg'],['양파',0.2,'kg'],['대파',0.2,'단'],['고춧가루',35,'g'],['국간장',25,'ml']],prep:['양파와 대파를 잘게 썹니다.'],steps:['냄비에 기름, 대파, 고춧가루를 넣고 약불에서 1분 볶습니다.','돼지고기와 양파를 넣고 고기가 익을 때까지 볶습니다.','물 1.5L와 국간장을 넣고 8분 끓입니다.','순두부를 큰 덩어리로 떠 넣고 5분 끓입니다.','계란을 넣고 2분 익힌 뒤 간을 맞춥니다.'],tips:['고춧가루는 타기 쉬우므로 반드시 약불에서 볶습니다.']},
 '돈까스':{time:30,difficulty:'쉬움',summary:'냉동 돈까스를 바삭하게 조리하고 채소를 곁들이는 구성',ingredients:[['돈까스',6,'장'],['양배추',0.3,'통'],['돈까스소스',180,'ml']],prep:['양배추는 곱게 채 썰어 찬물에 10분 담갔다가 물기를 뺍니다.'],steps:['에어프라이어를 190도로 3분 예열합니다.','돈까스 양면에 기름을 아주 얇게 바릅니다.','겹치지 않게 넣고 190도에서 8분 조리합니다.','뒤집어 6~8분 더 조리합니다.','가장 두꺼운 부분을 잘라 속까지 뜨거운지 확인합니다.','양배추와 소스를 곁들입니다.'],tips:['제품 두께에 따라 마지막 2~3분은 상태를 확인하며 조절합니다.']},
 '김치볶음밥':{time:25,difficulty:'쉬움',summary:'김치를 충분히 볶아 신맛을 줄인 고슬고슬 볶음밥',ingredients:[['김치',0.5,'kg'],['계란',6,'개'],['밥',1.2,'kg'],['대파',0.2,'단'],['참기름',20,'ml']],prep:['김치는 잘게 썰고 국물은 따로 둡니다.','찬밥의 덩어리를 풀어 둡니다.'],steps:['팬에 기름과 대파를 넣고 중불에서 향을 냅니다.','김치를 넣고 5분간 충분히 볶습니다.','김치국물 3큰술과 설탕 약간을 넣습니다.','밥을 넣고 센 불에서 4분간 볶습니다.','참기름을 두르고 불을 끕니다.','계란 프라이를 올려 냅니다.'],tips:['밥을 넣은 뒤 주걱으로 누르기보다 자르듯 섞으면 고슬고슬합니다.']},
 '닭볶음탕':{time:55,difficulty:'보통',summary:'감자가 부서지지 않고 양념이 진하게 배는 닭볶음탕',ingredients:[['닭다리살',1.2,'kg'],['감자',0.7,'kg'],['양파',0.4,'kg'],['당근',0.3,'kg'],['고추장',80,'g'],['고춧가루',40,'g'],['진간장',80,'ml'],['설탕',35,'g']],prep:['닭은 끓는 물에 2분 데친 뒤 씻습니다.','감자는 크게, 양파와 당근은 큼직하게 썹니다.'],steps:['냄비에 닭과 물 1.5L를 넣고 센 불에서 끓입니다.','끓으면 양념을 넣고 중불에서 15분 끓입니다.','감자와 당근을 넣고 15분 더 끓입니다.','양파를 넣고 뚜껑을 열어 8분간 졸입니다.','국물이 걸쭉해지면 대파를 넣고 2분 끓입니다.'],tips:['감자는 모서리를 둥글게 깎으면 오래 끓여도 덜 부서집니다.']},
 '계란찜':{time:20,difficulty:'쉬움',summary:'구멍 없이 부드럽고 촉촉하게 익히는 계란찜',ingredients:[['계란',10,'개'],['물',0.6,'L'],['대파',0.1,'단'],['소금',8,'g']],prep:['계란은 알끈을 제거하고 곱게 풉니다.'],steps:['계란물에 물과 소금을 넣어 고루 섞습니다.','체에 한 번 내려 부드럽게 만듭니다.','냄비에 넣고 중약불에서 바닥을 긁듯 저어줍니다.','몽글몽글해지면 약불로 줄이고 뚜껑을 덮습니다.','7분간 익힌 뒤 대파를 올리고 2분 뜸을 들입니다.'],tips:['끓는 육수를 사용하면 더 빠르고 부드럽게 익습니다.']},
 '오징어볶음':{time:30,difficulty:'보통',summary:'오징이가 질겨지지 않도록 짧고 강하게 볶는 메뉴',ingredients:[['오징어',1,'kg'],['양파',0.4,'kg'],['대파',0.2,'단'],['양배추',0.3,'통'],['고추장',80,'g'],['고춧가루',35,'g'],['진간장',45,'ml'],['설탕',30,'g']],prep:['오징어는 물기를 제거하고 1.5cm 폭으로 썹니다.','채소는 비슷한 크기로 썹니다.'],steps:['양념 재료를 섞어 둡니다.','팬을 센 불로 2분간 달굽니다.','양파와 양배추를 넣고 2분 볶습니다.','오징어와 양념을 넣고 센 불에서 3분 이내로 볶습니다.','대파를 넣고 30초 더 볶은 뒤 바로 불을 끕니다.'],tips:['오징이는 오래 익힐수록 질겨지므로 총 조리시간을 짧게 유지합니다.']},
 '부대찌개':{time:35,difficulty:'쉬움',summary:'햄의 짠맛을 조절해 국물까지 부담 없이 먹는 부대찌개',ingredients:[['소시지',0.8,'kg'],['김치',0.5,'kg'],['두부',1,'모'],['라면사리',2,'개'],['대파',0.2,'단'],['고춧가루',30,'g'],['고추장',35,'g']],prep:['소시지는 뜨거운 물에 한 번 헹굽니다.','두부와 김치는 먹기 좋게 썹니다.'],steps:['넓은 냄비에 김치, 소시지, 두부를 보기 좋게 담습니다.','고추장과 고춧가루를 물 2L에 풀어 붓습니다.','센 불에서 끓기 시작하면 중불로 줄입니다.','10분 끓인 뒤 라면사리를 넣습니다.','사리가 익으면 대파를 올리고 간을 확인합니다.'],tips:['햄과 김치의 염도가 높아 소금은 마지막에만 추가합니다.']}
 },
 prices:{'돼지 앞다리살':11000,'양파':2200,'대파':2500,'김치':6500,'두부':1800,'닭다리살':9500,'양배추':5000,'고등어':4500,'감자':2500,'카레':3500,'삼겹살':19000,'상추':3500,'소불고기':24000,'순두부':1500,'계란':350,'돈까스':2200,'오징어':14000,'소시지':12000,'식빵':450,'우유':2500,'슬라이스치즈':600,'버터':25,'쌀':3500,'당근':2500,'참기름':15000,'참치캔':2500,'김가루':30000,'마요네즈':5000,'바나나':700,'밥':2000,'식용유':4000,'슬라이스햄':700,'오트밀':5000,'견과류':16000,'콩나물':3000,'고추장':6000,'고춧가루':18000,'진간장':3000,'설탕':1800,'다진마늘':9000,'레몬':1200,'고구마':4000,'마늘':9000,'쌈장':6000,'배즙':3000,'돈까스소스':5000,'라면사리':900},
 units:{'돈까스':'장','고등어':'토막','계란':'개','두부':'모','순두부':'봉','카레':'팩','상추':'봉','대파':'단','양배추':'통','식빵':'장','우유':'L','슬라이스치즈':'장','버터':'g','쌀':'kg','당근':'kg','참기름':'ml','참치캔':'캔','김가루':'g','마요네즈':'g','바나나':'개','밥':'kg','식용유':'ml','슬라이스햄':'장','오트밀':'kg','견과류':'g','콩나물':'kg'}
};

function defaultState(){return {people:6,currentMonth:demoPlan.month,plans:{[demoPlan.month]:demoPlan},inventory:[
 {id:uid(),name:'삼겹살',qty:2.4,unit:'kg',location:'냉동실',min:1},
 {id:uid(),name:'계란',qty:24,unit:'개',location:'냉장실',min:12},
 {id:uid(),name:'양파',qty:3,unit:'kg',location:'실온',min:1},
 {id:uid(),name:'김치',qty:6,unit:'kg',location:'김치냉장고',min:2}
],mealChecks:{},shoppingChecks:{}}}
let state=load(); let phase=1; let deferredPrompt=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||defaultState()}catch{return defaultState()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function plan(){return state.plans[state.currentMonth]||null}
function factor(){return state.people/(plan()?.basePeople||6)}
function inventoryMap(){return Object.fromEntries(state.inventory.map(x=>[x.name,x]))}
function requirements(){const p=plan();if(!p)return {};const out={};p.meals.forEach(m=>[m.breakfast,m.lunch,m.dinner].filter(Boolean).forEach(name=>{const r=p.recipes[name];if(!r)return;r.ingredients.forEach(([n,q,u])=>{const key=n+'|'+u;out[key]=(out[key]||0)+q*factor()})}));return out}
function shoppingItems(){const p=plan();if(!p)return [];const inv=inventoryMap();return Object.entries(requirements()).map(([key,needed])=>{const [name,unit]=key.split('|');const have=inv[name]?.unit===unit?inv[name].qty:0;const buy=Math.max(0,needed-have);const price=p.prices[name]||0;return {name,unit,needed,have,buy,phase: shelfPhase(name),cost:buy*price}}).filter(x=>x.buy>0.001)}
function shelfPhase(name){return ['우유','두부','순두부','상추','콩나물','숙주','바나나'].some(x=>name.includes(x))?2:1}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}

function renderAll(){document.querySelector('#monthPicker').value=state.currentMonth;document.querySelector('#peopleSelect').value=String(state.people);renderHome();renderMeals();renderShopping();renderInventory()}
function renderHome(){const p=plan(), today=new Date(), day=(today.toISOString().slice(0,7)===state.currentMonth)?today.getDate():1;const m=p?.meals.find(x=>x.day===day)||p?.meals[0];const card=document.querySelector('#todayCard');
 if(!p){card.innerHTML='<h2>등록된 식단이 없습니다</h2><p>설정에서 월간 JSON을 가져오세요.</p>';return}
 const mealCard=(k,label)=>{const name=m[k],id=`${state.currentMonth}-${m.day}-${k}`,done=!!state.mealChecks[id];return `<article class="today-meal ${done?'done':''}"><div class="today-meal-head"><div><span class="meal-label">${label}</span><h3>${esc(name)}</h3></div><span class="meal-status">${done?'완료':'예정'}</span></div><div class="today-meal-actions"><button class="recipe-btn" onclick="showRecipe('${encodeURIComponent(name)}')">레시피 보기</button><button class="cook-btn" ${done?'disabled':''} onclick="completeHomeMeal('${id}','${encodeURIComponent(name)}')">${done?'조리 완료됨':'조리 완료'}</button></div></article>`};
 card.innerHTML=`<div class="date">${esc(state.currentMonth)} · ${day}일</div><h2>오늘 해야 할 것</h2><div class="today-meals">${mealCard('breakfast','아침')}${mealCard('lunch','점심')}${mealCard('dinner','저녁')}</div>`;
 const items=shoppingItems();document.querySelector('#budgetTotal').textContent=money(items.reduce((s,x)=>s+x.cost,0));document.querySelector('#needCount').textContent=items.length+'개';document.querySelector('#lowStockCount').textContent=state.inventory.filter(x=>x.qty<=x.min).length+'개';document.querySelector('#cookedCount').textContent=Object.values(state.mealChecks).filter(Boolean).length+'회';
 const tm=p.meals.find(x=>x.day===Math.min(day+1,p.meals.length));document.querySelector('#tomorrowPrep').textContent=tm?`${tm.day}일: ${tm.prep||'별도 준비 없음'}`:'다음 식단이 없습니다.'}
function renderMeals(){const p=plan(), box=document.querySelector('#mealList');if(!p){box.innerHTML='<div class="empty">식단을 가져오세요.</div>';return}box.innerHTML=p.meals.map(m=>`<article class="item"><div class="item-top"><div><h3>${m.day}일</h3><div class="meta">${esc(m.prep||'')}</div></div></div><div class="meal-actions">${[['breakfast','아침'],['lunch','점심'],['dinner','저녁']].map(([k,label])=>{const id=`${state.currentMonth}-${m.day}-${k}`,done=!!state.mealChecks[id];return `<div class="meal-action ${done?'done':''}"><label>${label} · ${esc(m[k])}</label><div><button onclick="showRecipe('${encodeURIComponent(m[k])}')">보기</button><input class="check" type="checkbox" ${done?'checked':''} onchange="toggleMeal('${id}','${encodeURIComponent(m[k])}',this.checked)"></div></div>`}).join('')}</div></article>`).join('')}
function renderShopping(){const list=shoppingItems().filter(x=>x.phase===phase), box=document.querySelector('#shoppingList');document.querySelector('#shoppingHint').textContent=`${state.people}명 기준 · 재고 차감 반영`;if(!list.length){box.innerHTML='<div class="empty card">구매할 품목이 없습니다.</div>';return}box.innerHTML=list.map(x=>{const id=`${state.currentMonth}-${phase}-${x.name}`,done=!!state.shoppingChecks[id];return `<article class="item shopping-row ${done?'done':''}"><input class="check" type="checkbox" ${done?'checked':''} onchange="toggleShopping('${id}','${encodeURIComponent(x.name)}',${x.buy},'${x.unit}',this.checked)"><div><h3>${esc(x.name)}</h3><div class="meta">필요 ${x.needed.toFixed(2)}${x.unit} − 재고 ${x.have.toFixed(2)}${x.unit}</div><div class="budget">예상 ${money(x.cost)}</div></div><div class="qty">${x.buy.toFixed(2)}${x.unit}</div></article>`}).join('')}
function renderInventory(){const box=document.querySelector('#inventoryList');if(!state.inventory.length){box.innerHTML='<div class="empty card">등록된 재고가 없습니다.</div>';return}box.innerHTML=state.inventory.sort((a,b)=>a.location.localeCompare(b.location)||a.name.localeCompare(b.name)).map(x=>`<article class="item ${x.qty<=x.min?'stock-low':'stock-ok'}"><div class="item-top"><div><h3>${esc(x.name)}</h3><div class="meta">${esc(x.location)} · 최소 ${x.min}${esc(x.unit)}</div></div><strong>${x.qty.toFixed(2)}${esc(x.unit)}</strong></div><div class="stock-controls"><button class="secondary" onclick="adjustStock('${x.id}',-1)">−1</button><button class="secondary" onclick="adjustStock('${x.id}',1)">+1</button><button class="text-btn" onclick="editInventory('${x.id}')">수정</button><button class="text-btn" onclick="deleteInventory('${x.id}')">삭제</button></div></article>`).join('')}


window.completeHomeMeal=function(id,encoded){if(state.mealChecks[id])return;if(confirm('조리 완료로 처리하고 사용 재료를 재고에서 차감할까요?'))toggleMeal(id,encoded,true)}

window.showRecipe=function(encoded){const name=decodeURIComponent(encoded),r=plan()?.recipes[name];document.querySelector('#recipeTitle').textContent=name;if(!r){document.querySelector('#recipeBody').innerHTML='<p>등록된 레시피가 없습니다.</p>';document.querySelector('#recipeDialog').showModal();return}const qty=(q)=>{const v=q*factor();return Number.isInteger(v)?String(v):v.toFixed(v<10?2:1).replace(/\.0+$|(?<=\.[0-9])0$/,'')};document.querySelector('#recipeBody').innerHTML=`<div class="recipe-summary"><p>${esc(r.summary||'')}</p><div class="recipe-meta"><span>⏱ ${esc(r.time||'-')}분</span><span>난이도 ${esc(r.difficulty||'-')}</span><span>${state.people}명 기준</span></div></div><h3>준비 재료</h3><ul class="recipe-ingredients detailed">${r.ingredients.map(([n,q,u])=>`<li><span>${esc(n)}</span><strong>${qty(q)}${esc(u)}</strong></li>`).join('')}</ul>${r.prep?.length?`<h3>조리 전 준비</h3><ul class="recipe-prep">${r.prep.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`:''}<h3>조리 순서</h3><ol class="recipe-steps detailed">${r.steps.map((s,i)=>`<li><span class="step-no">${i+1}</span><span>${esc(s)}</span></li>`).join('')}</ol>${r.tips?.length?`<div class="recipe-tips"><h3>실패 줄이는 팁</h3><ul>${r.tips.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div>`:''}${r.serving?`<div class="recipe-serving"><strong>곁들이기</strong><p>${esc(r.serving)}</p></div>`:''}`;document.querySelector('#recipeDialog').showModal()}
window.toggleMeal=function(id,encoded,checked){state.mealChecks[id]=checked;if(checked){const name=decodeURIComponent(encoded),r=plan()?.recipes[name];if(r){const inv=inventoryMap();r.ingredients.forEach(([n,q,u])=>{if(inv[n]&&inv[n].unit===u)inv[n].qty=Math.max(0,inv[n].qty-q*factor())})}toast('조리 완료 및 재고 차감')}save()}
window.toggleShopping=function(id,encoded,qty,unit,checked){state.shoppingChecks[id]=checked;if(checked){const name=decodeURIComponent(encoded);let item=state.inventory.find(x=>x.name===name&&x.unit===unit);if(item)item.qty+=qty;else state.inventory.push({id:uid(),name,qty,unit,location:'미지정',min:0});toast('구매 완료 및 재고 추가')}save()}
window.adjustStock=function(id,d){const x=state.inventory.find(x=>x.id===id);if(x){x.qty=Math.max(0,x.qty+d);save()}}
window.editInventory=function(id){const x=state.inventory.find(x=>x.id===id);if(!x)return;invId.value=x.id;invName.value=x.name;invQty.value=x.qty;invUnit.value=x.unit;invLocation.value=x.location;invMin.value=x.min;inventoryDialog.showModal()}
window.deleteInventory=function(id){if(confirm('이 재료를 삭제할까요?')){state.inventory=state.inventory.filter(x=>x.id!==id);save()}}

function download(obj,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function readJson(file){return JSON.parse(await file.text())}
function validPlan(p){return p&&typeof p.month==='string'&&Array.isArray(p.meals)&&p.recipes&&typeof p.recipes==='object'}

document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.page).classList.add('active')});
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{phase=Number(b.dataset.phase);document.querySelectorAll('.segmented button').forEach(x=>x.classList.toggle('active',x===b));renderShopping()});
monthPicker.onchange=e=>{state.currentMonth=e.target.value;save()};peopleSelect.onchange=e=>{state.people=Number(e.target.value);save()};resetMealChecks.onclick=()=>{if(confirm('현재 조리 체크를 모두 초기화할까요?')){Object.keys(state.mealChecks).filter(k=>k.startsWith(state.currentMonth)).forEach(k=>delete state.mealChecks[k]);save()}};
addInventoryBtn.onclick=()=>{inventoryForm.reset();invId.value='';invMin.value=0;inventoryDialog.showModal()};saveInventory.onclick=e=>{e.preventDefault();if(!inventoryForm.reportValidity())return;const data={id:invId.value||uid(),name:invName.value.trim(),qty:Number(invQty.value),unit:invUnit.value.trim(),location:invLocation.value,min:Number(invMin.value||0)};const idx=state.inventory.findIndex(x=>x.id===data.id);if(idx>=0)state.inventory[idx]=data;else state.inventory.push(data);inventoryDialog.close();save();toast('재고 저장')};closeRecipe.onclick=()=>recipeDialog.close();
importFile.onchange=async e=>{try{const p=await readJson(e.target.files[0]);if(!validPlan(p))throw new Error('형식 오류');state.plans[p.month]=p;state.currentMonth=p.month;save();toast('월간 식단을 가져왔습니다')}catch(err){alert('올바른 월간 식단 JSON 파일이 아닙니다.')}};
downloadSample.onclick=()=>{const p=plan();if(p)download(p,`${p.month}-월간식단.json`)};exportBackup.onclick=()=>download(state,`우리집식단-전체백업-${new Date().toISOString().slice(0,10)}.json`);restoreBackup.onchange=async e=>{try{const d=await readJson(e.target.files[0]);if(!d.plans||!Array.isArray(d.inventory))throw new Error();state=d;save();toast('전체 백업 복원 완료')}catch{alert('올바른 전체 백업 파일이 아닙니다.')}};resetAll.onclick=()=>{if(confirm('모든 식단·재고·체크 데이터를 삭제할까요?')){state=defaultState();save()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden')}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderAll();
